- name: Bisq 2 - Oracle Node Setup
  hosts: my_hosts

  tasks:
   - name: Install JDK 11 for bisq-daonode
     ansible.builtin.apt:
       name: openjdk-11-jdk
       state: present
     become: true

   - name: Clone bisq-daonode
     ansible.builtin.git:
       repo: https://github.com/bisq-network/bisq-daonode.git
       dest: /home/user/bisq-daonode
       single_branch: yes
       version: main

   - name: Build bisq-daonode
     ansible.builtin.command:
       chdir: /home/user/bisq-daonode
       cmd: ./gradlew build --no-daemon

   - name: Install bisq-daonode systemd service
     ansible.builtin.template:
       src: bisq-daonode.service.j2
       dest: /etc/systemd/system/bisq-daonode.service
       owner: root
       group: root
       mode: '0644'
     become: true
