name: Build Bisq 2

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build_bisq:
    name: Build Bisq on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    uses: ./.github/workflows/build_bisq_module.yml
    with:
      os: ${{ matrix.os }}
      name: Bisq
      build-root-dir: .

  build_network_module:
    name: Build network module on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    uses: ./.github/workflows/build_bisq_module.yml
    with:
      os: ${{ matrix.os }}
      name: network module
      build-root-dir: network

  build_tor_module:
    name: Build tor module on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    uses: ./.github/workflows/build_bisq_module.yml
    with:
      os: ${{ matrix.os }}
      name: tor module
      build-root-dir: network/tor

  build_wallet_module:
    name: Build wallet module on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    uses: ./.github/workflows/build_bisq_module.yml
    with:
      os: ${{ matrix.os }}
      name: wallet module
      build-root-dir: wallets